version: '3.8'

services:
  db:
    image: gvenzl/oracle-free
    ports:
      - 1521:1521
    environment:
      - ORACLE_PASSWORD=12345
    volumes:
      - oracle-data:/opt/oracle/oradata

volumes:
  oracle-data: